

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: empresa_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "5000:5000"
